# Generated by Django 4.1.5 on 2023-07-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_feedbacks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='image',
            field=models.ImageField(blank=True, default='uploaded_images/default.png/', null=True, upload_to=''),
        ),
    ]
